### ISSUE TITLE
How to get the text file in Indoor-Location-Navigation-Public/data/ including leaderboard_type.csv?

### ISSUE THREAD

**Issue by YoonaYaa** [ttvand/Indoor-Location-Navigation-Public#3]
Congrats 1st place in this competition! This is an amazing solution and thanks for sharing!

I'm wondering about how to get the text file in Indoor-Location-Navigation-Public/data/ including leaderboard_type.csv, non_parametric_wifi - valid - 2021-03-30 091444.csv, submission_cost_minimization.csv, test - 2021-05-15 051944.csv. 

At the beginning of the whole program, I found that you copy the text file mentioned above and I dont know how to get these files and is there any code to build these files?

I am a beginner in indoor localization and looking forward to your reply!

Thanks!

**Comment by ttvand** [comment]
The data is all here: https://github.com/ttvand/Indoor-Location-Navigation-Public/tree/master/data and you don't need to copy manually. Please follow the instructions in the main README file and create a separate data folder as you will need ~150GB of disk storage. I would recommend to use an external hard drive.

**Comment by YoonaYaa** [comment]
Thank you for your reply! I mean the data here: https://github.com/ttvand/Indoor-Location-Navigation-Public/tree/master/data  seems not build by the code in this repository and they are not provided by the official. I want to know how to build these files or which part of code build these files. Knowing the meaning of these files is important for me to understand the code.

I'm sorry that my English is not good and my expression is not clear.

**Comment by ttvand** [comment]
Some of these files come from the competition files and kernels (https://www.kaggle.com/c/indoor-location-navigation). The leaderboard type comes from probing the leaderboard, and the other files can be generated by the main script itself. They are simply there to speed up the execution time, since the models themselves are quite small.

**Comment by YoonaYaa** [comment]
Thank you very much!
